mod common;

use common::Harness;
use crossterm::event::KeyCode;

#[test]
fn test_menu_navigation_and_view_transitions() {
    let mut h = Harness::new();

    // Initial render
    assert_snapshot!(h, @r###"
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                    ╭ Splice Rust ─────────────────────────╮                    "
    "                    │> View git log                        │                    "
    "                    │  View files                          │                    "
    "                    │  Settings                            │                    "
    "                    │  Help                                │                    "
    "                    │  Quit                                │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    ╰──────────────────────────────────────╯                    "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "###);

    // Press 'j' - navigate down
    h.press(KeyCode::Char('j'));
    assert_snapshot!(h, @r###"
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                    ╭ Splice Rust ─────────────────────────╮                    "
    "                    │  View git log                        │                    "
    "                    │> View files                          │                    "
    "                    │  Settings                            │                    "
    "                    │  Help                                │                    "
    "                    │  Quit                                │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    ╰──────────────────────────────────────╯                    "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "###);

    // Press Enter - enter files view
    h.press(KeyCode::Enter);
    assert_snapshot!(h, @r###"
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "             ╭ Files ────────────────────────────────────────────╮              "
    "             │> internal/app/model.go                            │              "
    "             │  internal/core/messages.go                        │              "
    "             │  internal/git/commands.go                         │              "
    "             │  internal/ui/states/log/state.go                  │              "
    "             │  internal/ui/states/log/view.go                   │              "
    "             │  internal/ui/components/commit_list.go            │              "
    "             │  go.mod                                           │              "
    "             │  go.sum                                           │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             ╰───────────────────────────────────────────────────╯              "
    "                                                                                "
    "                                                                                "
    "                    ↑/↓ or j/k: navigate | Esc: back | q: qu                    "
    "                                                                                "
    "###);

    // Press 'j' - navigate within files
    h.press(KeyCode::Char('j'));
    assert_snapshot!(h, @r###"
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "             ╭ Files ────────────────────────────────────────────╮              "
    "             │  internal/app/model.go                            │              "
    "             │> internal/core/messages.go                        │              "
    "             │  internal/git/commands.go                         │              "
    "             │  internal/ui/states/log/state.go                  │              "
    "             │  internal/ui/states/log/view.go                   │              "
    "             │  internal/ui/components/commit_list.go            │              "
    "             │  go.mod                                           │              "
    "             │  go.sum                                           │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             │                                                   │              "
    "             ╰───────────────────────────────────────────────────╯              "
    "                                                                                "
    "                                                                                "
    "                    ↑/↓ or j/k: navigate | Esc: back | q: qu                    "
    "                                                                                "
    "###);

    // Press Esc - back to menu
    h.press(KeyCode::Esc);
    assert_snapshot!(h, @r###"
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                    ╭ Splice Rust ─────────────────────────╮                    "
    "                    │  View git log                        │                    "
    "                    │> View files                          │                    "
    "                    │  Settings                            │                    "
    "                    │  Help                                │                    "
    "                    │  Quit                                │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    │                                      │                    "
    "                    ╰──────────────────────────────────────╯                    "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "                                                                                "
    "###);
}
